import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BookOpen, Check, ChevronDown, Clock3, Filter, Layers3, LockKeyhole, LogOut, Menu, Plus, RotateCcw, Search, Sparkles, Trash2, X } from 'lucide-react';
import { emptyEntry, pluralPatterns, type Entry, type WordType } from './types';
import './style.css';

type View = 'library' | 'review' | 'insights';
type ApiResponse = { ok?: boolean; error?: string; entries?: Entry[]; entry?: Entry };
async function api(path: string, options?: RequestInit) {
  const response = await fetch(path, { cache: 'no-store', headers: { 'Content-Type': 'application/json' }, ...options });
  const data = await response.json() as ApiResponse;
  if (!response.ok || data.ok === false) throw new Error(data.error || 'Something went wrong.');
  return data;
}
function titleCase(value: string) { return value.charAt(0).toUpperCase() + value.slice(1); }
function due(entry: Entry, now = Date.now()) { return entry.confidence !== 'proficient' && (!entry.dueAt || new Date(entry.dueAt).getTime() <= now); }
function articleClass(article: string) { return article === 'der' ? 'blue' : article === 'die' ? 'rose' : 'gold'; }
function routeLabel(route: string) { return route === 'E' ? 'English link' : route === 'T' ? 'Memory trick' : route === 'S' ? 'Story' : 'No route yet'; }
function wordDisplay(entry: Entry) { return entry.type === 'noun' && entry.article ? `${entry.article} ${entry.word}` : entry.word; }
function compactDate(value: string) { return value ? new Date(value).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) : '—'; }

function App() {
  const [auth, setAuth] = useState<'loading' | 'locked' | 'open'>('loading');
  const [password, setPassword] = useState('');
  const [entries, setEntries] = useState<Entry[]>([]);
  const [view, setView] = useState<View>('library');
  const [search, setSearch] = useState('');
  const [typeFilter, setTypeFilter] = useState<'all' | WordType>('all');
  const [routeFilter, setRouteFilter] = useState('all');
  const [difficultyFilter, setDifficultyFilter] = useState('all');
  const [drawer, setDrawer] = useState<Entry | null>(null);
  const [selected, setSelected] = useState<Entry | null>(null);
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [reviewIndex, setReviewIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 60_000); return () => window.clearInterval(timer); }, []);

  async function load() {
    setLoading(true);
    try { const data = await api('/api/entries'); setEntries(data.entries || []); setMessage(''); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Could not load vocabulary.'); }
    finally { setLoading(false); }
  }
  useEffect(() => {
    api('/api/auth').then(() => { setAuth('open'); load(); }).catch(() => setAuth('locked'));
  }, []);
  const filtered = useMemo(() => entries.filter(e => {
    const q = search.trim().toLocaleLowerCase();
    const matches = !q || [e.word, e.meaning, e.article, e.plural, e.mnemonic, e.storyGroup, e.tags, e.notes].some(v => (v || '').toLocaleLowerCase().includes(q));
    return matches && (typeFilter === 'all' || e.type === typeFilter) && (routeFilter === 'all' || e.memoryRoute === routeFilter) && (difficultyFilter === 'all' || e.difficulty === difficultyFilter);
  }).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), [entries, search, typeFilter, routeFilter, difficultyFilter]);
  const dueEntries = useMemo(() => entries.filter(e => due(e, now)).sort((a, b) => (a.dueAt || '').localeCompare(b.dueAt || '')), [entries, now]);
  const reviewed = entries.filter(e => e.confidence === 'proficient').length;
  const nouns = entries.filter(e => e.type === 'noun');
  const storyGroups = [...new Set(nouns.map(e => e.storyGroup.trim()).filter(Boolean))];
  const currentReview = dueEntries[Math.min(reviewIndex, dueEntries.length - 1)];
  async function login(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setMessage('');
    try { await api('/api/auth', { method: 'POST', body: JSON.stringify({ password }) }); setAuth('open'); setPassword(''); await load(); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Could not unlock.'); }
    finally { setBusy(false); }
  }
  async function logout() { await api('/api/auth', { method: 'DELETE' }); setEntries([]); setAuth('locked'); setView('library'); }
  async function save(entry: Entry) {
    setBusy(true); setMessage('');
    try {
      const data = await api('/api/entries', { method: 'POST', body: JSON.stringify({ action: entry.id ? 'update' : 'create', id: entry.id, entry }) });
      if (!data.entry) throw new Error('The entry was not returned.');
      setEntries(prev => entry.id ? prev.map(e => e.id === entry.id ? data.entry! : e) : [data.entry!, ...prev]);
      setDrawer(null); setSelected(data.entry); setView('library');
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not save entry.'); }
    finally { setBusy(false); }
  }
  async function remove(entry: Entry) {
    if (!window.confirm(`Delete “${wordDisplay(entry)}”? This also removes its review history.`)) return;
    setBusy(true);
    try { await api('/api/entries', { method: 'POST', body: JSON.stringify({ action: 'delete', id: entry.id }) }); setEntries(prev => prev.filter(e => e.id !== entry.id)); setSelected(null); setDrawer(null); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Could not delete entry.'); }
    finally { setBusy(false); }
  }
  async function rate(rating: 'hard' | 'medium' | 'easy') {
    if (!currentReview) return;
    setBusy(true);
    try {
      const data = await api('/api/entries', { method: 'POST', body: JSON.stringify({ action: 'review', id: currentReview.id, rating }) });
      if (data.entry) setEntries(prev => prev.map(e => e.id === data.entry!.id ? data.entry! : e));
      setRevealed(false); setReviewIndex(0);
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not save review.'); }
    finally { setBusy(false); }
  }
  function navigate(next: View) { setView(next); setSelected(null); setMobileNav(false); setMessage(''); }
  if (auth === 'loading') return <div className="splash"><div className="brand-mark">W<span>.</span></div><p>Opening your wordbook…</p></div>;
  if (auth === 'locked') return <div className="lock-layout"><div className="lock-art"><div className="art-glow"/><div className="art-content"><span className="eyebrow light">YOUR PERSONAL GERMAN WORKSPACE</span><div className="art-word">Wörter<br/><em>bleiben.</em></div><p>Collect a word. Connect it to a story.<br/>Remember it when you need it.</p><div className="art-tiles"><span>der Gedanke</span><span>die Erinnerung</span><span>das Wort</span></div></div></div><div className="lock-form-wrap"><form className="lock-form" onSubmit={login}><div className="brand"><div className="brand-mark">W<span>.</span></div><div><strong>Wortwerk</strong><small>YOUR VOCABULARY STUDIO</small></div></div><div className="lock-icon"><LockKeyhole size={23}/></div><span className="eyebrow">WELCOME BACK</span><h1>Your words,<br/><em>all in one place.</em></h1><p>Enter your password to open your private German vocabulary library.</p><label htmlFor="password">Password</label><input id="password" autoFocus type="password" autoComplete="current-password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Enter your password" required/><button className="primary wide" disabled={busy} type="submit">{busy ? 'Unlocking…' : 'Open my wordbook'} <ArrowRight size={17}/></button>{message && <div className="notice error">{message}</div>}</form></div></div>;
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'show' : ''}`}><div className="side-top"><div className="brand"><div className="brand-mark">W<span>.</span></div><div><strong>Wortwerk</strong><small>VOCABULARY STUDIO</small></div></div><button className="mobile-close icon-button" onClick={() => setMobileNav(false)} aria-label="Close menu"><X size={20}/></button></div><div className="side-rule"/><div className="side-label">WORKSPACE</div><nav><button className={view === 'library' ? 'active' : ''} onClick={() => navigate('library')}><BookOpen size={18}/> My vocabulary <span className="nav-count">{entries.length}</span></button><button className={view === 'review' ? 'active' : ''} onClick={() => navigate('review')}><RotateCcw size={18}/> Review session {dueEntries.length > 0 && <span className="nav-count accent">{dueEntries.length}</span>}</button><button className={view === 'insights' ? 'active' : ''} onClick={() => navigate('insights')}><Layers3 size={18}/> Learning map</button></nav><div className="side-bottom"><div className="side-tip"><Sparkles size={18}/><strong>A little, often.</strong><p>Short reviews turn new words into familiar ones.</p></div><button className="logout" onClick={logout}><LogOut size={17}/> Lock wordbook</button></div></aside>
    <main className="main"><header className="topbar"><button className="mobile-menu icon-button" onClick={() => setMobileNav(true)} aria-label="Open menu"><Menu size={20}/></button><span className="breadcrumb">MY WORKSPACE <span>/</span> {view === 'library' ? 'VOCABULARY' : view === 'review' ? 'REVIEW' : 'LEARNING MAP'}</span><div className="top-right"><span className="top-dot"/> PRIVATE WORDBOOK <button className="avatar" aria-label="Account">S</button></div></header>
      {message && <div className="notice error page-notice">{message}<button onClick={() => setMessage('')} aria-label="Dismiss"><X size={15}/></button></div>}
      {view === 'library' && <div className="page-content"><div className="page-heading"><div><span className="eyebrow">DEIN WORTSCHATZ · YOUR WORD BANK</span><h1>Every word has<br/><em>a way to stay.</em></h1><p>Give new vocabulary a meaning, a memory, and a place to return to.</p></div><button className="primary add-main" onClick={() => { setMessage(''); setDrawer({ ...emptyEntry }); }}><Plus size={18}/> Add a word</button></div>
        <div className="stats-grid"><Stat icon={<BookOpen size={19}/>} label="WORDS COLLECTED" value={entries.length} detail="Your growing library" tint="sky"/><Stat icon={<Clock3 size={19}/>} label="READY TO REVIEW" value={dueEntries.length} detail={dueEntries.length ? 'A quick session awaits' : 'All caught up'} tint="amber"/><Stat icon={<Check size={19}/>} label="PROFICIENT WORDS" value={reviewed} detail="Ready to use" tint="mint"/></div>
        <div className="section-heading"><div><span className="eyebrow">THE COLLECTION</span><h2>My vocabulary <span className="heading-count">{filtered.length}</span></h2></div><button className="text-action" onClick={load} disabled={loading}><RotateCcw size={15} className={loading ? 'spin' : ''}/> Refresh</button></div>
        <div className="toolbar"><div className="search"><Search size={18}/><input placeholder="Search words, meanings, stories…" value={search} onChange={e => setSearch(e.target.value)}/>{search && <button onClick={() => setSearch('')} aria-label="Clear search"><X size={15}/></button>}</div><div className="select-wrap"><Filter size={16}/><select value={typeFilter} onChange={e => setTypeFilter(e.target.value as typeof typeFilter)} aria-label="Filter by word type"><option value="all">All types</option><option value="noun">Nouns</option><option value="verb">Verbs</option><option value="other">Other</option></select><ChevronDown size={14}/></div><div className="select-wrap"><select value={difficultyFilter} onChange={e => setDifficultyFilter(e.target.value)} aria-label="Filter by difficulty"><option value="all">All difficulty</option><option value="hard">Hard</option><option value="medium">Medium</option><option value="easy">Easy</option><option value="unrated">Unrated</option></select><ChevronDown size={14}/></div><div className="select-wrap"><select value={routeFilter} onChange={e => setRouteFilter(e.target.value)} aria-label="Filter by memory route"><option value="all">All routes</option><option value="E">E · English</option><option value="T">T · Trick</option><option value="S">S · Story</option><option value="">Unassigned</option></select><ChevronDown size={14}/></div></div>
        {entries.length === 0 ? <div className="empty-state"><div className="empty-graphic"><BookOpen size={38}/></div><span className="eyebrow">A FRESH PAGE</span><h3>Your wordbook starts here.</h3><p>Capture the next word you meet. Its article, plural, and memory trick can all live together.</p><button className="primary" onClick={() => { setMessage(''); setDrawer({ ...emptyEntry }); }}><Plus size={17}/> Add your first word</button></div> : filtered.length === 0 ? <div className="empty-state small"><Search size={30}/><h3>No words found</h3><p>Try a different search or filter.</p><button className="outline" onClick={() => { setSearch(''); setTypeFilter('all'); setRouteFilter('all'); setDifficultyFilter('all'); }}>Clear filters</button></div> : <div className="word-list"><div className="list-head"><span>WORD & MEANING</span><span>MEMORY PATH</span><span>PROGRESS</span><span>ADDED</span></div>{filtered.map(e => <button key={e.id} className="word-row" onClick={() => setSelected(e)}><div className="word-main"><span className={`article-icon ${e.type === 'noun' ? articleClass(e.article) : 'neutral'}`}>{e.type === 'noun' ? (e.article ? e.article.slice(0,1).toUpperCase() : 'N') : e.type === 'verb' ? 'V' : 'W'}</span><div><strong>{wordDisplay(e)}</strong><small>{e.meaning}</small></div></div><div><span className={`route-pill ${e.memoryRoute ? e.memoryRoute.toLowerCase() : 'muted'}`}>{e.memoryRoute || '·'} <span>{routeLabel(e.memoryRoute)}</span></span></div><div><span className={`status-dot ${due(e) ? 'due' : 'done'}`}/>{e.confidence === 'proficient' ? 'Proficient' : e.difficulty === 'unrated' ? 'New · due' : `${titleCase(e.difficulty)} · ${due(e) ? 'due' : 'scheduled'}`}</div><div className="date-cell">{compactDate(e.createdAt)} <ArrowRight size={16}/></div></button>)}</div>}
      </div>}
      {view === 'review' && <div className="page-content review-page"><div className="page-heading"><div><span className="eyebrow">A FEW MINUTES GO A LONG WAY</span><h1>Make it <em>stick.</em></h1><p>Recall the meaning before you flip the card. Your answers set the next review date.</p></div><div className="review-count"><span>{dueEntries.length}</span> WORDS DUE</div></div>{!currentReview ? <div className="empty-state review-empty"><div className="empty-graphic"><Check size={40}/></div><span className="eyebrow">NICELY DONE</span><h3>You’re all caught up.</h3><p>New words and review cards will appear here when they’re ready.</p><button className="primary" onClick={() => navigate('library')}>Back to vocabulary <ArrowRight size={16}/></button></div> : <div className="review-wrap"><div className="review-top"><span>CARD {Math.min(reviewIndex + 1, dueEntries.length)} OF {dueEntries.length}</span><div className="progress-track"><div style={{ width: `${Math.max(8, ((reviewIndex + 1) / dueEntries.length) * 100)}%` }}/></div></div><div className="flashcard"><span className="eyebrow">WHAT DOES THIS MEAN?</span><div className="flash-word">{wordDisplay(currentReview)}</div><div className="flash-type">{titleCase(currentReview.type)}{currentReview.type === 'noun' && currentReview.plural ? ` · plural: ${currentReview.plural}` : ''}</div>{revealed ? <div className="answer"><span className="eyebrow">THE ANSWER</span><h3>{currentReview.meaning}</h3>{currentReview.mnemonic && <p><Sparkles size={16}/> {currentReview.mnemonic}</p>}{currentReview.example && <blockquote>{currentReview.example}</blockquote>}</div> : <button className="outline reveal" onClick={() => setRevealed(true)}>Show meaning <ArrowRight size={16}/></button>}</div>{revealed && <div className="rating-row"><span>How well did you remember?</span><div><button disabled={busy} className="rating again" onClick={() => rate('hard')}>Hard <small>10 min</small></button><button disabled={busy} className="rating good" onClick={() => rate('medium')}>Medium <small>1+ days</small></button><button disabled={busy} className="rating easy" onClick={() => rate('easy')}>Easy <small>Much later</small></button></div></div>}</div>}</div>}
      {view === 'insights' && <div className="page-content"><div className="page-heading"><div><span className="eyebrow">SEE HOW YOU REMEMBER</span><h1>Your learning <em>map.</em></h1><p>Small patterns in your collection make the next word easier to place.</p></div></div><div className="insights-grid"><div className="insight-card"><span className="eyebrow">YOUR MEMORY ROUTES</span><h2>Where words find a home</h2><p>From your LP Grammar notes: E for an English link, T for a trick, S for a shared story.</p>{[['E','English link'],['T','Memory trick'],['S','Story']].map(([key,label]) => { const count = nouns.filter(e => e.memoryRoute === key).length; return <div className="bar-row" key={key}><span className={`route-circle ${key.toLowerCase()}`}>{key}</span><div><div className="bar-label"><strong>{label}</strong><span>{count} words</span></div><div className="bar-track"><div style={{width: `${nouns.length ? Math.max(2, count/nouns.length*100) : 0}%`}}/></div></div></div>; })}</div><div className="insight-card"><span className="eyebrow">YOUR NOUNS</span><h2>Articles at a glance</h2><p>Keep an eye on the genders you’ve collected.</p><div className="gender-grid">{['der','die','das'].map(a => <div key={a} className={`gender-tile ${articleClass(a)}`}><strong>{nouns.filter(e => e.article === a).length}</strong><span>{a}</span></div>)}</div><div className="insight-foot">{nouns.filter(e => !e.article).length} noun{nouns.filter(e => !e.article).length === 1 ? '' : 's'} still need an article.</div></div><div className="insight-card"><span className="eyebrow">CURRENT DIFFICULTY</span><h2>Words that need attention</h2><p>Each review records how difficult the word feels right now.</p>{[['hard','Hard'],['medium','Medium'],['easy','Easy']].map(([key,label]) => { const count = entries.filter(e => e.difficulty === key && e.confidence !== 'proficient').length; return <div className="bar-row" key={key}><span className={`route-circle ${key === 'hard' ? 't' : key === 'medium' ? 's' : 'e'}`}>{key[0].toUpperCase()}</span><div><div className="bar-label"><strong>{label}</strong><span>{count} words</span></div><div className="bar-track"><div style={{width: `${entries.length ? Math.max(2, count/entries.length*100) : 0}%`}}/></div></div></div>; })}</div><div className="insight-card full"><span className="eyebrow">STORIES THAT GROW</span><h2>Memory story groups</h2><p>Group masculine, feminine, and neuter words into editable stories, as suggested in your notes.</p>{storyGroups.length ? <div className="story-list">{storyGroups.map(group => <button key={group} onClick={() => { setSearch(group); navigate('library'); }}><span className="story-icon"><Sparkles size={18}/></span><span><strong>{group}</strong><small>{nouns.filter(e => e.storyGroup === group).length} connected words</small></span><ArrowRight size={17}/></button>)}</div> : <div className="story-placeholder">Add a story group to a noun to see your connected words here.</div>}</div></div></div>}
    </main>
    <nav className="bottom-nav" aria-label="Mobile navigation"><button className={view === 'library' ? 'active' : ''} onClick={() => navigate('library')}><BookOpen size={19}/><span>Words</span></button><button className={view === 'review' ? 'active' : ''} onClick={() => navigate('review')}><RotateCcw size={19}/><span>Review</span>{dueEntries.length > 0 && <i>{dueEntries.length}</i>}</button><button className="bottom-add" onClick={() => { setSelected(null); setMessage(''); setDrawer({ ...emptyEntry }); }} aria-label="Add a word"><Plus size={23}/></button><button className={view === 'insights' ? 'active' : ''} onClick={() => navigate('insights')}><Layers3 size={19}/><span>Map</span></button><button onClick={() => setMobileNav(true)}><Menu size={19}/><span>More</span></button></nav>
    {selected && !drawer && <div className="overlay" onMouseDown={() => setSelected(null)}><div className="detail-panel" onMouseDown={e => e.stopPropagation()}><button className="panel-close icon-button" onClick={() => setSelected(null)} aria-label="Close"><X size={20}/></button><span className="eyebrow">WORD CARD</span><div className="detail-word"><span className={`article-icon large ${selected.type === 'noun' ? articleClass(selected.article) : 'neutral'}`}>{selected.type === 'noun' ? (selected.article ? selected.article.slice(0,1).toUpperCase() : 'N') : selected.type === 'verb' ? 'V' : 'W'}</span><div><h2>{wordDisplay(selected)}</h2><p>{selected.meaning}</p></div></div><div className="detail-actions"><button className="primary" onClick={() => { setMessage(''); setDrawer({ ...selected }); }}>Edit word <ArrowRight size={16}/></button><button className="outline icon-only" onClick={() => remove(selected)} aria-label="Delete word" disabled={busy}><Trash2 size={17}/></button></div><div className="detail-section"><span className="eyebrow">THE ESSENTIALS</span><div className="detail-grid"><Detail label="TYPE" value={titleCase(selected.type)}/>{selected.type === 'noun' && <><Detail label="ARTICLE" value={selected.article || 'Not set'}/><Detail label="PLURAL" value={selected.plural || 'Not set'}/><Detail label="PLURAL PATTERN" value={pluralPatterns.find(p => p[0] === selected.pluralPattern)?.[1] || 'Not set'}/></>}<Detail label="SOURCE" value={selected.source || 'Not set'}/><Detail label="DIFFICULTY" value={titleCase(selected.difficulty || 'unrated')}/><Detail label="PROGRESS" value={selected.confidence === 'proficient' ? 'Proficient' : `${selected.streak || 0} successful recalls`}/><Detail label="REVIEW" value={selected.confidence === 'proficient' ? 'Completed' : due(selected) ? 'Due now' : `Next ${compactDate(selected.dueAt)}`}/></div></div>{selected.memoryRoute && <div className="detail-section"><span className="eyebrow">MEMORY PATH · {selected.memoryRoute}</span><h3>{routeLabel(selected.memoryRoute)}</h3>{selected.mnemonic && <p>{selected.mnemonic}</p>}{selected.storyGroup && <div className="story-tag"><Sparkles size={15}/> {selected.storyGroup}</div>}</div>}{selected.example && <div className="detail-section"><span className="eyebrow">IN CONTEXT</span><blockquote>{selected.example}</blockquote></div>}{selected.notes && <div className="detail-section"><span className="eyebrow">YOUR NOTES</span><p>{selected.notes}</p></div>}{selected.tags && <div className="tag-list">{selected.tags.split(',').map(t => t.trim()).filter(Boolean).map(t => <span key={t}>{t}</span>)}</div>}<div className="detail-footer">Added {compactDate(selected.createdAt)} · Reviewed {selected.reviewCount} times</div></div></div>}
    {drawer && <Editor key={drawer.id || 'new'} entry={drawer} busy={busy} error={message} onSave={save} onClose={() => { setDrawer(null); setMessage(''); }} />}
  </div>;
}
function Stat({icon,label,value,detail,tint}:{icon:React.ReactNode;label:string;value:number;detail:string;tint:string}) { return <div className="stat-card"><div className={`stat-icon ${tint}`}>{icon}</div><span className="eyebrow">{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function Detail({label,value}:{label:string;value:string}) { return <div><small>{label}</small><strong>{value}</strong></div>; }
function Editor({entry,busy,error,onSave,onClose}:{entry:Entry;busy:boolean;error:string;onSave:(e:Entry)=>void;onClose:()=>void}) {
  const [form,setForm] = useState<Entry>(entry);
  const update = (field:keyof Entry,value:string) => setForm(prev => ({...prev,[field]:value}));
  const noun = form.type === 'noun';
  const routeHint = form.memoryRoute === 'E' ? 'What English word or familiar pattern helps you remember the article?' : form.memoryRoute === 'T' ? 'Describe the visual, rhyme, or trick that makes the gender memorable.' : form.memoryRoute === 'S' ? 'Add this word to a growing story for der, die, or das.' : 'Choose the best way to remember this word.';
  return <div className="overlay editor-overlay" onMouseDown={onClose}><div className="editor" onMouseDown={e => e.stopPropagation()}><div className="editor-head"><div><span className="eyebrow">YOUR WORD BANK</span><h2>{entry.id ? 'Edit this word' : 'Capture a new word'}</h2><p>Keep the useful details together. Fill in what you know now; return anytime.</p></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={21}/></button></div><form onSubmit={e => { e.preventDefault(); onSave(form); }}><div className="editor-body"><div className="form-section"><div className="form-section-title"><span>01</span><div><strong>The word</strong><small>Start with what you found and what it means.</small></div></div><div className="type-tabs">{(['noun','verb','other'] as WordType[]).map(type => <button key={type} type="button" className={form.type === type ? 'selected' : ''} onClick={() => update('type',type)}>{titleCase(type)}</button>)}</div><div className="field-row"><label>German word <b>*</b><input required maxLength={500} value={form.word} onChange={e => update('word',e.target.value)} placeholder={noun ? 'e.g. Wohnung' : 'e.g. verstehen'}/></label><label>English meaning <b>*</b><input required maxLength={500} value={form.meaning} onChange={e => update('meaning',e.target.value)} placeholder="e.g. apartment"/></label></div>{noun && <div className="field-row three"><label>Article<select value={form.article} onChange={e => update('article',e.target.value)}><option value="">Choose article</option><option value="der">der</option><option value="die">die</option><option value="das">das</option></select></label><label>Plural form<input value={form.plural} onChange={e => update('plural',e.target.value)} placeholder="e.g. Wohnungen"/></label><label>Plural pattern<select value={form.pluralPattern} onChange={e => update('pluralPattern',e.target.value)}><option value="">Choose pattern</option>{pluralPatterns.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>}</div>
  {noun && <div className="form-section"><div className="form-section-title"><span>02</span><div><strong>Make it memorable</strong><small>The E · T · S method from your class notes.</small></div></div><div className="route-cards">{[['E','English link','The word feels like English.'],['T','A trick','A cue makes the article stick.'],['S','A story','Connect it to a growing story.']].map(([key,label,desc]) => <button type="button" key={key} className={form.memoryRoute === key ? 'selected' : ''} onClick={() => update('memoryRoute',form.memoryRoute === key ? '' : key)}><span>{key}</span><strong>{label}</strong><small>{desc}</small></button>)}</div><label>Memory note<textarea rows={3} value={form.mnemonic} onChange={e => update('mnemonic',e.target.value)} placeholder={routeHint}/></label>{form.memoryRoute === 'S' && <label>Story group<input value={form.storyGroup} onChange={e => update('storyGroup',e.target.value)} placeholder="e.g. The feminine city"/><span className="field-help">Use the same group name on other words to connect them.</span></label>}</div>}
  <div className="form-section"><div className="form-section-title"><span>{noun ? '03' : '02'}</span><div><strong>Context & source</strong><small>A sentence or note can make recall much easier.</small></div></div><label>Example sentence<textarea rows={2} value={form.example} onChange={e => update('example',e.target.value)} placeholder="Use this word in a sentence…"/></label><label>Personal notes<textarea rows={2} value={form.notes} onChange={e => update('notes',e.target.value)} placeholder="Usage, related words, or something your teacher said…"/></label><div className="field-row"><label>Source<input value={form.source} onChange={e => update('source',e.target.value)} placeholder="e.g. Hueber Thesaurus"/></label><label>Tags <span className="optional">OPTIONAL</span><input value={form.tags} onChange={e => update('tags',e.target.value)} placeholder="e.g. home, chapter 3"/><span className="field-help">Separate tags with commas.</span></label></div></div></div><div className="editor-footer">{error && <div className="notice error">{error}</div>}<button type="button" className="outline" onClick={onClose}>Cancel</button><button className="primary" disabled={busy} type="submit">{busy ? 'Saving…' : entry.id ? 'Save changes' : 'Save word'} <ArrowRight size={16}/></button></div></form></div></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
